### ISSUE TITLE
TypeError: Cannot read property 'bot' of undefined

### ISSUE THREAD

**Issue by SamFeniks** [Dragory/modmailbot#133]
Hi!

Reinstalled the bot twice. redid the config twice. npm is uptodate. why am i getting this when a user dms the bot?

```
TypeError: Cannot read property 'bot' of undefined
    at CommandClient.bot.on (/root/android/modmailbot/src/modules/typingProxy.js:20:94)
    at CommandClient.emit (events.js:182:13)
    at Shard.emit (/root/android/modmailbot/node_modules/eris/lib/gateway/Shard.js:1877:26)
    at Shard.wsEvent (/root/android/modmailbot/node_modules/eris/lib/gateway/Shard.js:405:26)
    at Shard.onWSMessage (/root/android/modmailbot/node_modules/eris/lib/gateway/Shard.js:1716:26)
    at WebSocket.ws.onmessage (/root/android/modmailbot/node_modules/eris/lib/gateway/Shard.js:1593:33)
    at WebSocket.onMessage (/root/android/modmailbot/node_modules/ws/lib/EventTarget.js:99:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (/root/android/modmailbot/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/root/android/modmailbot/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/root/android/modmailbot/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/root/android/modmailbot/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/root/android/modmailbot/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/root/android/modmailbot/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
```

**Comment by Dragory** [comment]
Does this happen with every user who DMs the bot, or only specific ones?

**Comment by SamFeniks** [comment]
it seems to have stopped happening, or my pm2 is just killer fast at restarting. im going to leave it running like this for now
