### ISSUE TITLE
Error: Error reading config file! The error given was: JSON5: invalid character '\"' at 10:3

### ISSUE THREAD

**Issue by Skylekko** [Dragory/modmailbot#212]
The bot won't start because there's a backslash in the config ... apparently ... I tried looking for a backslash using Ctrl F and there isn't any so I'm a bit confused.

Error: Error reading config file! The error given was: JSON5: invalid character
'\"' at 10:3
    at Object.<anonymous> (C:\SOSB14119\src\config.js:39:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\SOSB14119\src\index.js:32:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)

C:\SOSB14119\src>

**Comment by iamBalliE** [comment]
I am having the same problem

**Comment by zain2k** [comment]
Me too please help me

**Comment by Dragory** [comment]
@iamBalliE @zain2k This error is caused by syntax errors in the config. You can use something like https://jsonlint.com/ to validate it (though remove your token from the config beforehand). If you're still getting this error after doing that, please open a new issue and include your config with it (though, again, without the token).
