### ISSUE TITLE
Error reading config file! The error given was: JSON5: invalid character '\"' at 11:3

### ISSUE THREAD

**Issue by ACA30** [Dragory/modmailbot#214]
/root/modmailbot/src/config.js:39
  throw new Error(`Error reading config file! The error given was: ${e.message}`);
  ^

Error: Error reading config file! The error given was: JSON5: invalid character '\"' at 11:3
    at Object.<anonymous> (/root/modmailbot/src/config.js:39:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/modmailbot/src/index.js:32:16)
    at Module._compile (module.js:652:30)

**Comment by ACA30** [comment]
config.json:
```{
  "token": "aisyhdftgiuasydgtkjhasgdkfiuyatswet",
  "mailGuildId": "539938895966502924",
  "mainGuildId": "539938895966502924",
  "logChannelId": "539964894536138792",
  "prefix": "-",
  "newThreadCategoryId": "539964375868637184",

  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! Our mod team will reply to you here as soon as possible."
  "allowUserClose": true,
  "botMentionResponse": "If you need support, please DM me!",
  "closeMessage": "Your thread has been closed. We hope you had a good experience! Feel free to contact us again if you have any further questions.",
  "ignoreAccidentalThreads": true,
  "mentionRole": "539942036699217942",
  "mentionUserInThreadHeader": true,
  "snippetPrefix": "--",
  "snippetPrefixAnon": "---",
  "threadTimestamps": true,
  "typingProxy": true,
  "typingProxyReverse": true,
}```

**Comment by ACA30** [comment]
Forgot a comma, found the error
