### ISSUE TITLE
Bot will randomly stop running

### ISSUE THREAD

**Issue by StreamersConnected** [Dragory/modmailbot#25]
Hello, for some reason after left idle the bot will stop running, any reason for this? I believe it's possibly because some mail go unanswered for hours.

**Comment by Dragory** [comment]
Are there any errors in the console when the bot shuts off? Threads that linger are not an issue, I've had plenty of those on multiple servers where I host modmail.

**Comment by StreamersConnected** [comment]
`
^E(node:9731) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 404 NOT FOUND on POST /channels/345194807536386049/messages

{"code": 10003, "message": "Unknown Channel"}
(node:9731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'id' of undefined
    at CommandClient.onMessageCreate (/home/daddy/modmailbot/node_modules/eris/lib/command/CommandClient.js:136:58)
    at emitOne (events.js:120:20)
    at CommandClient.emit (events.js:210:7)
    at Shard.wsEvent (/home/daddy/modmailbot/node_modules/eris/lib/gateway/Shard.js:394:33)
    at WebSocket.ws.onmessage (/home/daddy/modmailbot/node_modules/eris/lib/gateway/Shard.js:1462:34)
    at WebSocket.onMessage (/home/daddy/modmailbot/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/home/daddy/modmailbot/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/home/daddy/modmailbot/node_modules/ws/lib/Receiver.js:389:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daddy/.npm/_logs/2017-08-13T06_47_47_413Z-debug.log
`

This is what I get

**Comment by Dragory** [comment]
Have you deleted any of the modmail threads (the channels, e.g. #dragory-8537) manually? If so, that will break the bot, use `!close` instead.

A possible fix:
1. Shut down the bot
2. Delete `db/threads.json`
3. Delete all channels on the modmail inbox server *except* the default channel
4. Restart bot

**Comment by StreamersConnected** [comment]
Will do, also I don't know if this is relevant or not but there's two other channels in the modmail server, one for bot testing and another for bot logs, just so I can have an additional way of knowing who leaves/joins and name changes

**Comment by StreamersConnected** [comment]
I don't know if that'd cause this too, should I just remove those?

**Comment by StreamersConnected** [comment]
Debug logs 

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle modmailbot@1.0.0~prestart: modmailbot@1.0.0
6 info lifecycle modmailbot@1.0.0~start: modmailbot@1.0.0
7 verbose lifecycle modmailbot@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle modmailbot@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/daddy/modmailbot/node_modules/.bin:/home/daddy/bin:/home/daddy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle modmailbot@1.0.0~start: CWD: /home/daddy/modmailbot
10 silly lifecycle modmailbot@1.0.0~start: Args: [ '-c', 'node src/index.js' ]
11 silly lifecycle modmailbot@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle modmailbot@1.0.0~start: Failed to exec start script
13 verbose stack Error: modmailbot@1.0.0 start: `node src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid modmailbot@1.0.0
15 verbose cwd /home/daddy/modmailbot
16 verbose Linux 4.4.0-83-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error modmailbot@1.0.0 start: `node src/index.js`
22 error Exit status 1
23 error Failed at the modmailbot@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by StreamersConnected** [comment]
Ive deleted all the channels except for the default and its still happening

**Comment by StreamersConnected** [comment]
Bot started, listening to DMs
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'id' of undefined
    at CommandClient.onMessageCreate (/home/daddy/test/modmailbot/node_modules/eris/lib/command/CommandClient.js:136:58)
    at emitOne (events.js:120:20)
    at CommandClient.emit (events.js:210:7)
    at Shard.wsEvent (/home/daddy/test/modmailbot/node_modules/eris/lib/gateway/Shard.js:394:33)
    at WebSocket.ws.onmessage (/home/daddy/test/modmailbot/node_modules/eris/lib/gateway/Shard.js:1462:34)
    at WebSocket.onMessage (/home/daddy/test/modmailbot/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/home/daddy/test/modmailbot/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/home/daddy/test/modmailbot/node_modules/ws/lib/Receiver.js:389:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node src/index.js "app"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daddy/.npm/_logs/2017-08-18T09_45_02_465Z-debug.log
daddy@streconn:~/test/modmailbot$

**Comment by Dragory** [comment]
Hmm, this seems to be an issue in Eris (the Discord library I'm using), possibly related to the new "X has joined the server" welcome messages. It seems to trip on messages that don't have an author (e.g. system messages).

While we wait for a fix upstream for eris, you can disable these welcome messages by going to server settings and setting "new member messages channel" to "No New Member Messages" like so:

![image](https://user-images.githubusercontent.com/2606411/29468457-08ed8e70-844d-11e7-9585-e3961c1ffbef.png)

**Comment by StreamersConnected** [comment]
Alright I've done so, although the issue is still persisting and dying, giving me that error message.

**Comment by StreamersConnected** [comment]
Ive done all the steps, ive deleted hte threads.json, cleared all of the channel except for default, correctly closed the channel with !close and then set no to welcome messages... and the issue is still persisting for some reason

**Comment by StreamersConnected** [comment]
:\

**Comment by StreamersConnected** [comment]
im sad

**Comment by SHADOW6** [comment]
1) I have similar issue; it will constantly error out sys clock different from discords UTC time 
(an eris issue) despite fixes, it still happens A LOT

2)The bot will create empty text channels just before a crash, example Anon-1234.
 After restarting the bot if the same user msgs the bot it makes a 2nd user room Anon-1234
the bot has no checks if a room already exists. I dono if thats something easy to add.

3) currently unable to get npm start to work. the old start method works fine. But it will not reboot/restart if it gets an error (sys time mismatch).

>error from Git
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Your clock is 2572ms behind Discord's server clock. Please check your con
nection and system time.
    at ClientRequest.req.once (C:\Server Programs\Discord Bots\modmailbot-old\no
de_modules\eris\lib\rest\RequestHandler.js:170:56)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21
)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)

**Comment by Dragory** [comment]
@SHADOW6 

1 & 3) Make sure your computer's clock is synchonized

2) Checking if a room exists is done for channels that have been created without the bot crashing. I can't really check the channel name since it could result in collissions (since some names need to be transliterated into ASCII).

**Comment by Dragory** [comment]
Closing issue due to inactivity

**Comment by SKT-Light** [comment]
Error I got 
![Here](https://user-images.githubusercontent.com/33887756/50812275-21c45500-12e0-11e9-8254-8d953a87d623.png)
