### ISSUE TITLE
Discord.js: When ever I turn my computer to sleep it, it crashes.

### ISSUE THREAD

**Issue by Charps-Studios** [Dragory/modmailbot#280]
When my computer goes to sleep, it crashes with the log of

 throw err; // Unhandled 'error' event
    ^
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at CommandoClient.emit (events.js:171:17)
    at WebSocketConnection.onError (C:\Users\Charps\Mythical Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (C:\Users\Charps\Mythical Bot\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (C:\Users\Charps\Mythical Bot\node_modules\ws\lib\websocket.js:211:14)
    at Receiver.cleanup (C:\Users\Charps\Mythical Bot\node_modules\ws\lib\receiver.js:535:15)
    at WebSocket.finalize (C:\Users\Charps\Mythical Bot\node_modules\ws\lib\websocket.js:206:20)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

Can you please help?

**Comment by Jarifa** [comment]
The bot will not work when your computer goes asleep. You should prevent your pc from autosleeping.
