### ISSUE TITLE
Error: Invalid argument definition: <userId:userId>

### ISSUE THREAD

**Issue by crazyartz666** [Dragory/modmailbot#324]
Full Log
PS C:\Users\alpha\Desktop\modmailbot-2.25.0> npm install
audited 1462 packages in 5.758s
found 0 vulnerabilities

PS C:\Users\alpha\Desktop\modmailbot-2.25.0> node .                                                                     Loading plugins...
Error: Invalid argument definition: <userId:userId>
    at C:\Users\alpha\Desktop\modmailbot-2.25.0\node_modules\knub-command-manager\dist\CommandManager.js:188:23
    at Array.map (<anonymous>)
    at CommandManager.parseParameterString (C:\Users\alpha\Desktop\modmailbot-2.25.0\node_modules\knub-command-manager\dist\CommandManager.js:185:37)
    at CommandManager.add (C:\Users\alpha\Desktop\modmailbot-2.25.0\node_modules\knub-command-manager\dist\CommandManager.js:83:31)
    at Object.addInboxServerCommand (C:\Users\alpha\Desktop\modmailbot-2.25.0\src\commands.js:69:27)
    at module.exports (C:\Users\alpha\Desktop\modmailbot-2.25.0\src\modules\logs.js:57:12)
    at C:\Users\alpha\Desktop\modmailbot-2.25.0\src\main.js:226:7
    at Array.forEach (<anonymous>)
    at Object.start (C:\Users\alpha\Desktop\modmailbot-2.25.0\src\main.js:225:13)
    at C:\Users\alpha\Desktop\modmailbot-2.25.0\src\index.js:92:8
PS C:\Users\alpha\Desktop\modmailbot-2.25.0>

**Comment by sporkwitch** [comment]
Post your config file, without token
v / r
Robert Klebes
Mobile: 571-492-8639
https://keybase.io/sporkwitch
https://www.linkedin.com/in/klebes

**Comment by Dragory** [comment]
Can you try removing your `node_modules` folder and running `npm ci` instead of `npm install`?
