### ISSUE TITLE
node .

### ISSUE THREAD

**Issue by Bluead** [Dragory/modmailbot#361]
Im getting this after trying to do node .
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'C:\Users\tom\Desktop\modmailbot-master\node_modules\sqlite3\lib\binding\node-v79-win32-x64\node_sqlite3.node'
Require stack:
- C:\Users\tom\Desktop\modmailbot-master\node_modules\sqlite3\lib\sqlite3.js
- C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\dialects\sqlite3\index.js
- C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\index.js
- C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\knex.js
- C:\Users\tom\Desktop\modmailbot-master\src\knex.js
- C:\Users\tom\Desktop\modmailbot-master\src\main.js
- C:\Users\tom\Desktop\modmailbot-master\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\tom\Desktop\modmailbot-master\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Client_SQLite3._driver (C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\dialects\sqlite3\index.js:57:12)
    at Client_SQLite3.initializeDriver (C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\client.js:250:26)
    at Client_SQLite3.Client (C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\client.js:108:10)
    at new Client_SQLite3 (C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\dialects\sqlite3\index.js:42:20)
    at Knex (C:\Users\tom\Desktop\modmailbot-master\node_modules\knex\lib\index.js:56:34)

**Comment by clarionhoover** [comment]
It looks like you're running node-v79-win32-64 which would have the major version of node 13 and as it says in the setup docs node 13 is not supported. Please try installing node 10, node 11, or node 12 then trying again.

https://github.com/Dragory/modmailbot/blob/master/docs/setup.md#prerequisites < a link to the section that mentions this.
