### ISSUE TITLE
Websocket Error

### ISSUE THREAD

**Issue by Hamster-0001** [Dragory/modmailbot#377]
For some reason, a few hours after starting any of my bots using the modmailbot code; I encounter a websocket error.

` type: 'error',
message: 'WebSocket was closed before the connection was established',
error: Error: WebSocket was closed before the connection was established
at WebSocket.terminate (/home/container/node_modules/ws/lib/websocket.js:366:14)
at Shard.disconnect (/home/container/node_modules/eris/lib/gateway/Shard.js:99:25)
at Timeout._onTimeout (/home/container/node_modules/eris/lib/gateway/Shard.js:1671:22)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
}) `

**Comment by sporkwitch** [comment]
This is a not-unusual connectivity issue; the easiest solution is to simply use pm2 to automatically restart the bot if it crashes due to something like that.  There's a pm2 launchfile in the repo.
