### ISSUE TITLE
Sometimes the bot goes offline after a few days to a week

### ISSUE THREAD

**Issue by DogeMomentt** [Dragory/modmailbot#392]
Here is the error message:

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    readyState: 2,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    url: 'wss://gateway.discord.gg/?v=6&encoding=json',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo ENOTFOUND gateway.discord.gg',
  error: Error: getaddrinfo ENOTFOUND gateway.discord.gg
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'gateway.discord.gg'
  }
})
    at Client.emit (events.js:299:17)
    at Shard.emit (C:\Users\Big Lion\Desktop\modmailbot-master\node_modules\eris\lib\gateway\Shard.js:1866:26)
    at WebSocket.ws.onerror (C:\Users\Big Lion\Desktop\modmailbot-master\node_modules\eris\lib\gateway\Shard.js:1623:18)
    at WebSocket.onError (C:\Users\Big Lion\Desktop\modmailbot-master\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:310:20)
    at ClientRequest.<anonymous> (C:\Users\Big Lion\Desktop\modmailbot-master\node_modules\ws\lib\websocket.js:554:15)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: ErrorEvent {
    target: WebSocket {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      readyState: 2,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006,
      _extensions: {},
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      url: 'wss://gateway.discord.gg/?v=6&encoding=json',
      _req: null,
      [Symbol(kCapture)]: false
    },
    type: 'error',
    message: 'getaddrinfo ENOTFOUND gateway.discord.gg',
    error: Error: getaddrinfo ENOTFOUND gateway.discord.gg
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
      errno: 'ENOTFOUND',
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'gateway.discord.gg'
    }
  }
}

**Comment by Dragory** [comment]
Network errors can cause the bot to crash, as seems to have happened here. I would suggest hooking the bot up to something that restarts it automatically, such as `pm2`.
