### ISSUE TITLE
Error starting the bot!

### ISSUE THREAD

**Issue by kennygil123** [Dragory/modmailbot#40]
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

Thats the error plz help me! :)

**Comment by Dragory** [comment]
This is likely due to an old NodeJS version. Make sure you are using NodeJS **8** or higher!
