### ISSUE TITLE
Bot going offline for some reason again and again

### ISSUE THREAD

**Issue by SkillfulShoe781** [Dragory/modmailbot#41]
**events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Your clock is 10705ms behind Discord's server clock. Please check your connection and system time.
    at ClientRequest.req.once (C:\Users\Preksha\Documents\modmailbot-master\node_modules\eris\lib\rest\RequestHandler.js:167:56)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:549:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:438:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Preksha\AppData\Roaming\npm-cache\_logs\2017-10-20T09_32_15_649Z-debug.log**

I am getting that error some reason... I don't know what that means but the bot is going offline for some reason. What should I do?

**Comment by Dragory** [comment]
As far as I know, this issue happens when your machine's clock isn't properly synced. You seem to be using Windows, so this should definitely happen automatically. Have you tried again after you initially had this issue? Did you get the same error?
