### ISSUE TITLE
Bot started, after i went offline. It went offline and would not start back again. how do you make it stay online without being online yourself?

### ISSUE THREAD

**Issue by Skyxd97** [Dragory/modmailbot#42]
PS C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master\src> npm start

> modmailbot@1.0.0 start C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master
> node --trace-warnings src/index.js

C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master\src\config.js:6
  throw new Error(`Config file could not be found or read! The error given was: ${e.message}`);
  ^

Error: Config file could not be found or read! The error given was: C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master\config.json: Unexpected string in JSON at position 301
    at Object.<anonymous> (C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master\src\config.js:6:9)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master\src\index.js:6:16)
    at Module._compile (module.js:612:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shawn\AppData\Roaming\npm-cache\_logs\2017-10-26T11_11_35_424Z-debug.log
PS C:\Users\shawn\Downloads\modmailbot-master\modmailbot-master\src>

**Comment by judge2020** [comment]
Could you post your config.js file (but of course Removing your client id/secret)? The error is something with the syntax at line 6, position 9.
