### ISSUE TITLE
Error with Module "Move"

### ISSUE THREAD

**Issue by LordAlex2015** [Dragory/modmailbot#440]
My Error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rest/Endpoints.js' is not defined by "exports" in /home/container/node_modules/eris/package.json
at applyExports (internal/modules/cjs/loader.js:490:9)
at resolveExports (internal/modules/cjs/loader.js:506:23)
at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/container/src/modules/move.js:4:23)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

**Comment by Dragory** [comment]
Make sure you're using Node.js 12, not 13 or 14. For further help, please join the support server at https://discord.gg/vRuhG9R!
