### ISSUE TITLE
Bot crashes on attachments send

### ISSUE THREAD

**Issue by Trigonoculus** [Dragory/modmailbot#46]
Logs:
```rt@rt:~/modmailbot$ npm start --verbose                                                                                                                
npm info it worked if it ends with ok
npm verb cli [ '/home/linuxbrew/.linuxbrew/Cellar/node/9.3.0_1/bin/node',
npm verb cli   '/home/linuxbrew/.linuxbrew/bin/npm',
npm verb cli   'start',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v9.3.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle modmailbot@1.0.0~prestart: modmailbot@1.0.0
npm info lifecycle modmailbot@1.0.0~start: modmailbot@1.0.0

> modmailbot@1.0.0 start /home/rt/modmailbot
> node --trace-warnings src/index.js

Bot started, listening to DMs
events.js:180
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
    at _addListener (events.js:180:11)
    at WriteStream.addListener (events.js:240:10)
    at WriteStream.close (fs.js:2298:10)
    at WriteStream.writeStream.on (/home/rt/modmailbot/src/attachments.js:39:21)
    at WriteStream.emit (events.js:164:20)
    at finishMaybe (_stream_writable.js:616:14)
    at afterWrite (_stream_writable.js:467:3)
    at onwrite (_stream_writable.js:457:7)
    at fs.js:2287:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:2253:5)
npm verb lifecycle modmailbot@1.0.0~start: unsafe-perm in lifecycle true
npm verb lifecycle modmailbot@1.0.0~start: PATH: /home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rt/modmailbot/node_modules/.bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/rt/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin
npm verb lifecycle modmailbot@1.0.0~start: CWD: /home/rt/modmailbot
npm info lifecycle modmailbot@1.0.0~start: Failed to exec start script
npm verb stack Error: modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at EventEmitter.emit (events.js:159:13)
npm verb stack     at ChildProcess.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:159:13)
npm verb stack     at maybeClose (internal/child_process.js:943:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm verb pkgid modmailbot@1.0.0
npm verb cwd /home/rt/modmailbot
npm verb Linux 4.11.3-fvz-042stab124.2
npm verb argv "/home/linuxbrew/.linuxbrew/Cellar/node/9.3.0_1/bin/node" "/home/linuxbrew/.linuxbrew/bin/npm" "start" "--verbose"
npm verb node v9.3.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@1.0.0 start: `node --trace-warnings src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the modmailbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rt/.npm/_logs/2018-01-03T00_41_50_820Z-debug.log```

**Comment by Dragory** [comment]
Can you see if it works on Node 8? I haven't tested the bot on Node 9 yet.
Additionally, make sure you downloaded the `master` branch version of modmail bot, not the `experimental` branch.

**Comment by Trigonoculus** [comment]
Yep, it works on Node 8. Thanks for the quick response.
