### ISSUE TITLE
Error: Disallowed intents specified

### ISSUE THREAD

**Issue by vasolix** [Dragory/modmailbot#484]
Error: Disallowed intents specified
    at Shard._onWSClose (/root/Discord/Diamondevent/node_modules/eris/lib/gateway/Shard.js:1849:23)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.emitClose (/root/Discord/Diamondevent/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/root/Discord/Diamondevent/node_modules/ws/lib/websocket.js:858:15)
    at TLSSocket.emit (events.js:326:22)
    at net.js:672:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 4014
}

Voila tout 👍

**Comment by Eight8-7020** [comment]
Head over to the developer portal -> click on your application -> bot -> select allow intents
