### ISSUE TITLE
Hmm an unknown message error

### ISSUE THREAD

**Issue by ChillPlayz** [Dragory/modmailbot#489]
hmm i got this error saying this
DiscordRESTError [10008]: Unknown Message
    at RequestHandler.request (/home/container/node_modules/eris/lib/rest/RequestHandler.js:71:15)
    at Client.deleteMessage (/home/container/node_modules/eris/lib/Client.js:1231:36)
    at Message.delete (/home/container/node_modules/eris/lib/structures/Message.js:387:43)
    at commands.addInboxThreadCommand.aliases (/home/container/src/modules/reply.js:16:28)

any clue how to help?

**Comment by Dragory** [comment]
Do you have something (like another bot) that could be deleting the `!r` command message before modmail deletes it?

**Comment by BAARIFY** [comment]
I got the same error too, a day after I started hosting the bot. The error is
```
Error 10008: DiscordRESTError [10008]: Unknown Message
    at RequestHandler.request (/home/runner/Modmail/node_modules/eris/lib/rest/RequestHandler.js:76:15)
    at Client.deleteMessage (/home/runner/Modmail/node_modules/eris/lib/Client.js:743:36)
    at Message.delete (/home/runner/Modmail/node_modules/eris/lib/structures/Message.js:341:43)
    at commands.addInboxThreadCommand.aliases (/home/runner/Modmail/modules/reply.js:28:28)
```
This was the last message before the bot went down:
