### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by OmarWazzan** [Dragory/modmailbot#56]
```
`root@gtaodiscord:~/modmail# npm start

> modmailbot@2.1.0 start /root/modmail
> node src/index.js

Missing required config.json value: logChannelId
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@2.1.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T09_05_45_678Z-debug.log
root@gtaodiscord:~/modmail# npm start

> modmailbot@2.1.0 start /root/modmail
> node src/index.js

/root/modmail/src/data/Thread.js:254
      ...data
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/modmail/src/data/threads.js:12:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@2.1.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T09_06_58_504Z-debug.log`
```

After upgrading, the bot refuses to start and gives this error.

**Comment by OmarWazzan** [comment]
```
{
  "token": "Mzc1NDAxNzgyMzQxNTMzNzAw.DNvTqw.FWw2beNqU8d89s7mjriZyqX3t2M",
  "mailGuildId": "308456096178241536",
  "mainGuildId": "224565836277481473",
  "logChannelId": "308456096178241536",
  "port": "8891",

  "prefix": "!",
  "status": "Message me for help!",
  "responseMessage": "Thank you for your message! The mod team will reply to you here as soon as possible.",
  "ignoreAccidentalThreads": true,
  "useNicknames": true,
  "newThreadCategoryId": "378292086509928456",
  "typingProxy": true
} 
```

Copy of config.js if required

**Comment by Dragory** [comment]
Please make sure you're using NodeJS 8.9.4 or higher. The error it's giving is for code that wasn't supported in older versions of NodeJS.

Also, since you posted your token here publicly, you should reset it!

**Comment by OmarWazzan** [comment]
Right, I'll upgrade that now, and reset the token!

Thanks!

**Comment by Dragory** [comment]
After upgrading NodeJS, make sure to remove the `node_modules` folder and run `npm install` again - otherwise it may cause some issues.

**Comment by OmarWazzan** [comment]
```
root@gtaodiscord:~# tmux new -s modmail
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/root/modmailnew/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/root/modmailnew/node_modules/knex/lib/client.js:249:26)
    at Client_SQLite3.Client (/root/modmailnew/node_modules/knex/lib/client.js:126:10)
    at new Client_SQLite3 (/root/modmailnew/node_modules/knex/lib/dialects/sqlite3/index.js:62:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@2.1.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T14_34_43_862Z-debug.log
```

**Comment by Dragory** [comment]
Did you run `npm install` again? There's a new package (sqlite3) that it needs to install. If you did, try removing the `node_modules` folder and running `npm install` again.

**Comment by OmarWazzan** [comment]
Yup, removing the node_modules folder worked.

Thanks!

**Comment by OmarWazzan** [comment]
New modmail threads now do not contain a message, they start up blank.

```
[NOTE] Creating new thread channel midorina-0007
Error: insert into `threads` (`channel_id`, `created_at`, `id`, `is_legacy`, `status`, `user_id`, `user_name`) values ('417342065995939841', '2018-02-25 15:28:22', '1061848e-46f6-4c4f-9f29-014193715872', 0, 1, '90076279646212096', 'Midorina#0007') - SQLITE_READONLY: attempt to write a readonly database
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@2.1.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T15_28_22_530Z-debug.log
```

**Comment by Dragory** [comment]
Hmm, that's weird. Try running `chmod 0777 db/data.sqlite` and restarting the bot.

**Comment by OmarWazzan** [comment]
That fixed it.

Though now, there are no timestamps.

https://gtaodiscord.com/o/9e9baf.png

vs

https://gtaodiscord.com/o/deeae5.png

Is it an option now?

**Comment by Dragory** [comment]
Yeah, timestamps have been moved to an option called `threadTimestamps`. I removed them from the threads themselves as Discord already has its own timestamps, and the precise per-minute timestamps are rarely needed in most cases.

Note that logs will still always have accurate timestamps, regardless of the setting!

**Comment by OmarWazzan** [comment]
Thanks, much appreciated for all the help!
