### ISSUE TITLE
Blank (anonymous) snippet causes bot to crash.

### ISSUE THREAD

**Issue by kyle-wordpress** [Dragory/modmailbot#673]
Hello there. I believe to have found an unreported bug. Prefix is =

If you leave a snippet blank, then the bot will crash. Prefixes I am using (if this affects anything):
snippetPrefixAnon = =l
snippetPrefix = =lr

Other settings that may be conflicting:
alwaysReply = on
alwaysReplyAnon = on
dbType = mysql

More settings available upon request.

As you can see by the screenshot I am using the 'hello' snippet. I ran the snippet anonymously (=lhello) and normally (=lrhello), both working fine. As soon as I put the command blank (=lr) then the bot crashes. You can see me attempt to run the same command again with no success.

![image](https://user-images.githubusercontent.com/94929481/143088118-14d169c7-0b71-4a3b-a339-d680bcd9a3a2.png)

This is the exact error message:
Error: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Client.<anonymous> (/home/runner/modmailp/src/modules/snippets.js:63:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Thank you.

**Comment by kyle-wordpress** [comment]
Note: Type of database does not affect it. I tried it with a modmail bot with the same settings but the database was SQLite.

**Comment by kyle-wordpress** [comment]
No config needed, just tried it with !! and !!! on their own with the same error. 
Error: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Client.<anonymous> (/home/runner/#######/src/modules/snippets.js:63:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
