### ISSUE TITLE
Crash when reading property add

### ISSUE THREAD

**Issue by NoComment1105** [Dragory/modmailbot#713]
The bot crashes occasionally, with reasons I cannot quite work out.
```
Error: TypeError: Cannot read property 'add' of undefined
    at Shard.wsEvent (/home/ubuntu/modmail/node_modules/eris/lib/gateway/Shard.js:830:65)
    at Shard.onPacket (/home/ubuntu/modmail/node_modules/eris/lib/gateway/Shard.js:400:26)
    at Shard._onWSMessage (/home/ubuntu/modmail/node_modules/eris/lib/gateway/Shard.js:2169:29)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/ubuntu/modmail/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/home/ubuntu/modmail/node_modules/ws/lib/receiver.js:437:14)
    ...stack trace truncated to 8 lines
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! modmailbot@3.3.2 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the modmailbot@3.3.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-06-02T13_25_45_256Z-debug.log
```
This is the trimmed error log that is provided. there is nothing prior to the error message that details a failure of anything.

The full log is attached below:
[2022-06-02T13_25_45_256Z-debug.log](https://github.com/Dragory/modmailbot/files/8839768/2022-06-02T13_25_45_256Z-debug.log)

**Comment by Dragory** [comment]
This is caused by [Text Chat in Voice Channels](https://discord.com/blog/text-in-voice-chat-channel-announcement-tiv). The version of the bot you're using (v3.3.2) didn't yet support these properly, and crashed whenever a message was posted in them.

[Update to the newest bot version](https://github.com/Dragory/modmailbot/blob/master/docs/updating.md) to fix the problem!

**Comment by NoComment1105** [comment]
Aight thank you my friend
