### ISSUE TITLE
Suggestion: Downloadable Transcript

### ISSUE THREAD

**Issue by PokedArmory** [Dragory/modmailbot#724]
I don't like the transcript's being saved as a link, and I would rather have an option to save them as a downloadable file in a discord channel.

**Comment by Oliver-Akins** [comment]
This is already a feature by changing the `logStorage` option https://github.com/Dragory/modmailbot/blob/master/docs/configuration.md#logstorage

**Comment by PokedArmory** [comment]
I noticed that right after I posted this suggestion!

**Comment by PokedArmory** [comment]
```[NOTE] Creating new thread channel poked_armory-0001
Closing thread 33951ce7-66bd-4c00-b6fa-487f6ea48a30
Deleting channel 996650112136785930
Error ENOENT: Error: ENOENT: no such file or directory, open 'logs/33951ce7-66bd-4c00-b6fa-487f6ea48a30.txt'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at save (/home/container/src/data/logs.js:176:8)
    at async saveLogToStorage (/home/container/src/data/logs.js:88:25)
    at async /home/container/src/modules/logs.js:130:5
    at async callAfterThreadCloseHooks (/home/container/src/hooks/afterThreadClose.js:39:5)
    at async Thread.close (/home/container/src/data/Thread.js:773:5)
    at async Object.commands.addGlobalCommand.options.name (/home/container/src/modules/close.js:179:5)
```

**Comment by mesub7** [comment]
> ```
> Closing thread 33951ce7-66bd-4c00-b6fa-487f6ea48a30
> Deleting channel 996650112136785930
> Error ENOENT: Error: ENOENT: no such file or directory, open 'logs/33951ce7-66bd-4c00-b6fa-487f6ea48a30.txt'
>     at Object.openSync (node:fs:585:3)
>     at Object.writeFileSync (node:fs:2170:35)
>     at save (/home/container/src/data/logs.js:176:8)
>     at async saveLogToStorage (/home/container/src/data/logs.js:88:25)
>     at async /home/container/src/modules/logs.js:130:5
>     at async callAfterThreadCloseHooks (/home/container/src/hooks/afterThreadClose.js:39:5)
>     at async Thread.close (/home/container/src/data/Thread.js:773:5)
>     at async Object.commands.addGlobalCommand.options.name (/home/container/src/modules/close.js:179:5)
> ```

Was this thread already open prior to you making the change?

**Comment by PokedArmory** [comment]
@mesub7 I suggested it before I knew it already existed, but when I toggled the `logStorage` option I started receiving that error.

**Comment by mesub7** [comment]
> @mesub7 I suggested it before I knew it already existed, but when I toggled the `logStorage` option I started receiving that error.

Yes, I mean was the thread that is causing the error created before you changed `logStorage` in your config?

**Comment by PokedArmory** [comment]
@mesub7 I just deleted my SQLite database file and all the tickets, But I'm still having the issue. 

```
[NOTE] Creating new thread channel poked_armory-0001
Closing thread e5e6e01c-3a80-498a-b7a0-c803f835578f
Deleting channel 996844640273707140
Error ENOENT: Error: ENOENT: no such file or directory, open 'logs\e5e6e01c-3a80-498a-b7a0-c803f835578f.txt'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at save (C:\Users\PM780\Downloads\421fb328-e3b4-46b2-9d40-895c3cd5a130\src\data\logs.js:176:8)
    at async saveLogToStorage (C:\Users\PM780\Downloads\421fb328-e3b4-46b2-9d40-895c3cd5a130\src\data\logs.js:88:25)
    at async C:\Users\PM780\Downloads\421fb328-e3b4-46b2-9d40-895c3cd5a130\src\modules\logs.js:130:5
    at async callAfterThreadCloseHooks (C:\Users\PM780\Downloads\421fb328-e3b4-46b2-9d40-895c3cd5a130\src\hooks\afterThreadClose.js:39:5)
    at async Thread.close (C:\Users\PM780\Downloads\421fb328-e3b4-46b2-9d40-895c3cd5a130\src\data\Thread.js:773:5)
    at async Object.commands.addGlobalCommand.options.name (C:\Users\PM780\Downloads\421fb328-e3b4-46b2-9d40-895c3cd5a130\src\modules\close.js:179:5)
```

**Comment by mesub7** [comment]
In order to investigate this issue better, with quicker support, please visit the [discord server](https://discord.gg/vRuhG9R).
