### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'add')

### ISSUE THREAD

**Issue by ebullienc3** [Dragory/modmailbot#764]
[NOTE] Creating new thread channel ta1funa-9386
Closing thread 49d8dc4b-e60e-4d67-83aa-08c8222c106a
Deleting channel 1093239137429094470
Closing thread 19a0de58-0067-4a7b-a21d-01b7c5bec92d
Deleting channel 1090725698055970826
Error: TypeError: Cannot read properties of undefined (reading 'add')
    at Shard.wsEvent (D:\Bots\modmail\node_modules\eris\lib\gateway\Shard.js:854:65)
    at Shard.onPacket (D:\Bots\modmail\node_modules\eris\lib\gateway\Shard.js:403:26)
    at Shard._onWSMessage (D:\Bots\modmail\node_modules\eris\lib\gateway\Shard.js:2455:29)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (D:\Bots\modmail\node_modules\ws\lib\websocket.js:1169:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (D:\Bots\modmail\node_modules\ws\lib\receiver.js:528:14)
    ...stack trace truncated to 8 lines
Press any key to continue . . .

**Comment by ebullienc3** [comment]
Issue comes from the new Stage Channels and their text option. Just make the bot not to see those channels by permissions.
